### ISSUE TITLE
errors not working

### ISSUE THREAD

**Issue by umarana** [recurly/recurly-client-ruby#136]
```ruby
begin
      account = Recurly::Account.find(current_user.account_id)
      account.billing_info = {
        :number             => '4112-1111-1111w-1111',
        :verification_value => '123',
        :month              => 11,
        :year               => 2015
      }
      account.billing_info.save
rescue Recurly::Resource::NotFound => e
      puts e.message
rescue Recurly::Resource::UnprocessableEntity => e
      puts e.message
else
      puts "Successfully Created"
end
```

it will print "Successfully Created" event its not

**Comment by thbar** [comment]
@umarana are you still seeing the error? (implementing similar code at the moment, so I'm wondering). Thanks!

**Comment by jfitisoff** [comment]
I think this will work for error checking:

[6] pry(main)> account.billing_info.save!
Recurly::Resource::Invalid: number is not a valid credit card number

or this:

[8] pry(main)> account.billing_info.errors
=> {"number"=>["is not a valid credit card number"]}

**Comment by cbarton** [comment]
This is functioning as designed. In order for an exception to be thrown please use the bang version of the `save` method, as pointed out by @jfitisoff

**Comment by pavel-mihailovskiy** [comment]
Hello guys, I'm using the 2.4.9, but getting the same issue.

billing_info.save!
=> Recurly::Transaction::DeclinedError: Your card number is not valid. Please update your card number.

pry(#<BillingInfosController>)> billing_info.errors
=> {}

**Comment by bhelx** [comment]
@pavel-mihailovskiy transaction errors are different than invalid errors:

```ruby
begin
  account = Recurly::Account.find('test8')

  account.billing_info = {
    :number             => '4000-0000-0000-0051',
    :verification_value => '123',
    :month              => 11,
    :year               => 2018,
    :first_name         => 'A',
    :last_name          => 'B'

  }

  account.billing_info.save!
rescue Recurly::Resource::Invalid => e
  puts e.class
  puts e.message
  puts account.billing_info.errors
rescue Recurly::Transaction::DeclinedError => e
  puts e.transaction_error_code # invalid_card_number
  puts e.gateway_error_code
  puts e.message # Your card number is not valid. Please update your card number.
end
``

**Comment by bhelx** [comment]
@pavel-mihailovskiy does that work for you?

**Comment by pavel-mihailovskiy** [comment]
@bhelx yes, that works for me, thanks a lot!
