### ISSUE TITLE
Net::ReadTimeout setting shorter timeout?

### ISSUE THREAD

**Issue by andrewarrow** [recurly/recurly-client-ruby#146]
I tried changing the Recurly::API.base_uri value to

http://localhost:3001/

and made a small rails app that just simulates a long hanging http connection. I eventually get a Net::ReadTimeout error but it takes over a minute I think.  (Default value I guess?)

Can I change this to 5 seconds or something super short? If recurly is down last thing I want is for various parts of my site (not related to payment) to also be down.

[UPDATE: I guess I can just wrap my code in Timeout::timeout(5) do]

**Comment by bhelx** [comment]
I believe this can be set by changing the net_http params. For example, say you wanted to timeout the tcp connection process after 5 seconds and timeout a read after 30 seconds:

```ruby
Recurly::API.net_http = {
  open_timeout: 5,
  read_timeout: 30
}
```

As you can see here, we iterate over the hash and set any net/http params given:

https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/api/net_http_adapter.rb#L23

Here is a list of possible params:

http://ruby-doc.org/stdlib-2.2.2/libdoc/net/http/rdoc/Net/HTTP.html

Please re-open if you think that doesn't fully answer your question or does not work for you.
