### ISSUE TITLE
Threadsafe Recurly.api_key?

### ISSUE THREAD

**Issue by ivanovv** [recurly/recurly-client-ruby#159]
We develop metrics app for Recurly, and extensively use threads (through Sidekiq). We have Braintree and Stripe integration in place and we’re working on getting Recurly live. But there is a problem - https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/api/net_http_adapter.rb#L47 is not threadsafe, and two operations running in parallel will use the same api key (even if started for different clients).

Any chances to make Recurly thread safe?
Will you accept a PR?

**Comment by thbar** [comment]
@ivanovv apart from this specific API key issue, since you appear to use Recurly in a multi-threaded setup, did you meet other thread-safety issues?

**Comment by ivanovv** [comment]
@thbar we use [Sidekiq](https://github.com/mperham/sidekiq)  as a multithreaded background job solution, and no thread-safety issues for the last 6 months. But we mainly use this lib in readonly mode, so YMMV.

**Comment by thbar** [comment]
@ivanovv thanks for the feedback, appreciated!

**Comment by bhelx** [comment]
Closed with: https://github.com/recurly/recurly-client-ruby/pull/190
