### ISSUE TITLE
Recurly should escape urls for paged resources

### ISSUE THREAD

**Issue by ivanovv** [recurly/recurly-client-ruby#174]
When we call ```resource#find```, gem escapes URLs via  ```member_path```
```ruby
def member_path uuid
  uuid = ERB::Util.url_encode(uuid) if uuid
  [collection_path, uuid].compact.join '/'
end
```
But when we call ```pager#find```, gem passes uuid without escaping it - https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/pager.rb#L176

The result is an error similar to ```bad URI(is not URI?): https://api.recurly.com/v2/plans/access-annual2/add_ons/Golden Pro Annual```

tmp fix is to use the same URL escaping
```ruby
plan.add_ons.find(ERB::Util.url_encode(adjustment.product_code))
```

**Comment by ivanovv** [comment]
related to #92 I guess

**Comment by austinheap** [comment]
Hi @ivanovv, thanks for reporting the issue. We're looking into this internally and will update you soon.

**Comment by austinheap** [comment]
@ivanovv this has been fixed. Please let me know if you are still encountering issues.
