### ISSUE TITLE
Retrieve account balance

### ISSUE THREAD

**Issue by gawin** [recurly/recurly-client-ruby#178]
The Recurly web interface shows an account 'Balance'.
The account balance is essential when using metered billing and verifying credit charges, especially if they are not invoiced yet.

Unfortunately the value of the account balance doesn't seem retrievable through the API.
By retracting the invoices total_in_cents from the adjustments total_in_cents one can calculate the same value; the account balance.

```ruby
account = Recurly::Account.find('1')

def balance_in_cents(account)
  adjustments = account.adjustments.map{|x|x.total_in_cents}.inject(:+) || 0
  invoices    = account.invoices.map{|x|x.total_in_cents}.inject(:+) || 0
  adjustments - invoices
end
```

This works, but feels error-prone, is expensive and really slow.
Could you please expose the balance through the API and ruby client.

**Comment by edann** [comment]
Hi Gawin,

Thanks for your comment. We are planning to expose this through our API shortly. Currently, it's available in APIv1. If you have any interest in trying out our future APIs, please let me know and I can add you to the beta program!

Cheers,
Emma Dannin
emma@recurly.com

**Comment by gawin** [comment]
Hi Emma,

Thank you for your response and pointer to the API v1.

Workaround using API v1, might help someone else one day:

```ruby
require 'recurly'
require 'nokogiri'

# Configure Recurly
Recurly::API.class_variable_set(:@@base_uri, 'https://api.recurly.com/')
Recurly.subdomain        = '...'
Recurly.api_key          = '...'

# Retrieve the account balance for account with ID 1
response         = Recurly::API.get 'accounts/1'
xml              = Nokogiri::Slop(response.body)
balance_in_cents = xml.css("account balance_in_cents").inner_text.to_i
```

Looking forward to the official exposure of 'balance_in_cents' in the new release.

**Comment by bhelx** [comment]
@gawin balance_in_cents is currently not implemented in the API. If you are still having an issue with this please feel free to re-open and I'd be happy to discuss other possible solutions.

**Comment by kaleemullah** [comment]
@bhelx can you please recommend any efficient solution? Thanks.

**Comment by bhelx** [comment]
@kaleemullah after looking into it, I don't think there is. This is an outstanding API issue that we have yet to get enough momentum to get implemented. I can think of a couple ways to implement this on the API level but it would need to be prioritized as a problem. If you think this is something you can't live without I would suggest contacting our support team and link this issue. That would help tip this over the edge.

**Comment by DrOhReally** [comment]
I am also extremely interested in this as my client requires a way to display credit remaining in the account section. :)

**Comment by bhelx** [comment]
We will be providing a solution for this in the next release:

https://github.com/recurly/recurly-client-ruby/pull/253
