### ISSUE TITLE
CC data for a transaction

### ISSUE THREAD

**Issue by firehawkcreative** [recurly/recurly-client-ruby#179]
When retrieving a transaction, there doesn't seem to be a way to access the CC info for that transaction. The API does return it in the XML, but it's not accessible with the gem.

**Comment by austinheap** [comment]
Hi @firehawkcreative. Could you tell what fields are you referring to that you're unable to access?

**Comment by firehawkcreative** [comment]
I'm sorry, my mistake, I figured it out:

transaction.details['account'].billing_info.card_type

That works for me fine.

Sorry about that.
