### ISSUE TITLE
Incorrect request type or error in documentation

### ISSUE THREAD

**Issue by AlexParamonov** [recurly/recurly-client-ruby#182]
On the https://docs.recurly.com/api/billing-info#update-billing-info-token
described a way to update billing information.

`PUT https://:subdomain.recurly.com/v2/accounts/:account_code/billing_info`

and given a Ruby example:
```
account = Recurly::Account.find('1')
account.billing_info = {
  token_id: 'TOKEN_ID'
}
account.billing_info.save
```

Which in turn send a POST request.
I took me some time to debug and find that issue is actually not on my side, but on Ruby Recurly library.

**Comment by whiteotter** [comment]
Hi Alex, we'll be updating the docs to the following to ensure a PUT call on pre-existing records

```
account = Recurly::Account.find('1')
account.billing_info.token_id = 'TOKEN_ID'
account.billing_info.save
```

**Comment by AlexParamonov** [comment]
:+1:

**Comment by bhelx** [comment]
Thanks for reporting @AlexParamonov

**Comment by whiteotter** [comment]
updated docs now live at https://docs.recurly.com/api/billing-info#update-billing-info-token
