### ISSUE TITLE
Nil billing info

### ISSUE THREAD

**Issue by AlexParamonov** [recurly/recurly-client-ruby#183]
When account does not have billing info attached, Ruby library returns nil:

```
account.billing_info
```

But after
```
account.billing_info = { account: account }
```
or 
```
account.billing_info = { token_id: "abc" }
```

It remains `nil`

**Comment by chrissrogers** [comment]
I think in this instance you will need to initialize a new BillingInfo in place of the `nil`.

```ruby
account.build_billing_info token_id: 'abc'
```

**Comment by AlexParamonov** [comment]
ok, that make sense.
It will be good to have it in docs as well.
