### ISSUE TITLE
More specific errors

### ISSUE THREAD

**Issue by byronduenas** [recurly/recurly-client-ruby#184]
Right now when an object (like Subscription) fails to create, "Recurly::API::UnprocessableEntity" will only return a generic "account is invalid" error. It would be great if I can get the element (e.g. zip code, missing country, etc) with the specific error, without having to manually parse the xml data at "errors".

**Comment by austinheap** [comment]
Hi @byronduenas, thank you for your feedback. Our SDKs do not provide this pattern and implementers need to iterate over the errors hash that is provided on the object that was unprocessable.

An example hash that explains the errors might look like:

    {"address1"=>["can't be empty"], "city"=>["can't be empty"], "country"=>["can't be empty"], "number"=>["is required"], "zip"=>["can't be empty"]}

Please contact support if you encounter errors with this pattern. Thank you.

**Comment by cgerrior** [comment]
An example of this method of exception handling can be found [here](https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource.rb#L57-L65).
