### ISSUE TITLE
Cannot create first plan addon

### ISSUE THREAD

**Issue by jakolehm** [recurly/recurly-client-ruby#200]
`Plan#add_ons` returns array when plan does not have any addons. This causes error when trying to add one using `plan.add_ons.create`. 

Maybe this is documentation bug but it would be nice to get always same behaviour when accessing `has_many` associations?

**Comment by bhelx** [comment]
@jakolehm thanks for reporting

I'm going to take a look at this. I would expect `plan.add_ons.create` so I could see how that could be confusing.

**Comment by bhelx** [comment]
@jakolehm I can't seem to replicate the problem. Here is the code I am using:

```ruby
plan = Recurly::Plan.find('addonless')
add_on = plan.add_ons.create(
  add_on_code: 'ipaddresses',
  name: 'Extra IP Addresses',
  unit_amount_in_cents: 2_00
)
```

where `addonless` is the plan without any addons. It doesn't throw any errors, properly creates the `add_on` instance, and creates the add on in Recurly.

Could you paste some code replicating the issue and if possible paste any errors you are seeing? There may be a subtle difference in your code that is causing the problem. Could you also let me know which version of the library you are using?

**Comment by jakolehm** [comment]
It seems that this happens only when plan is fetched through subscription:

```ruby
plan = subscription.plan
add_on = plan.add_ons.create(
  add_on_code: 'ipaddresses',
  name: 'Extra IP Addresses',
  unit_amount_in_cents: 2_00
)
=> NoMethodError: undefined method `create' for []:Array
```

It works if plan is fetched through `Recurly::Plan#find` .

**Comment by jakolehm** [comment]
Forgot to mention that this happens with latest version (2.4.4)

**Comment by bhelx** [comment]
@jakolehm Okay, I've replicated the problem. I'm going to look into seeing if there is a good fix for this in the next couple days. In the meantime if you want to get your code working you could try this:

```ruby
subscription = Recurly::Subscription.find('2fe91d24476e34dd2d7f884354842010')
plan = subscription.plan
plan.reload
add_on = plan.add_ons.create(
  add_on_code: 'ipaddresses',
  name: 'Extra IP Addresses',
  unit_amount_in_cents: 2_00
)
puts add_on
```

**Comment by jeropaul** [comment]
Is there a timeframe for fixing this?

I'd like to do something like:
    subscription = Recurly::Account.find('account id').subscriptions.active.first
    subscription.add_ons = subscription.add_ons <<  subscription.plan.add_ons.find('add_on_code')
    suscription.preview()

I'll use your work around for the time being

**Comment by bhelx** [comment]
@jeropaul That's a slightly different issue I think:

https://github.com/recurly/recurly-client-ruby/issues/220

The method `<<` actually takes a string for the add on code:
https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/subscription/add_ons.rb#L20

You'd want to do something like this:
```ruby
 subscription.add_ons = subscription.add_ons << 'add_on_code'
```
Further more, `<<` mutates the array rather than returning one. This is how it works in ruby and our library:

```ruby
subscription.add_ons << 'add_on_code'
```

**Comment by bhelx** [comment]
@jeropaul  let me know if that works for you. I understand it's not very well documented or intuitive.

**Comment by bhelx** [comment]
Closing for now. Please re-open if we need further discussion.
