### ISSUE TITLE
Account id starting with dot causes client to fail

### ISSUE THREAD

**Issue by ivanovv** [recurly/recurly-client-ruby#201]
Recurly::Account.find('.some-account')
```
===> GET https://api.recurly.com/v2/accounts/.some-account
{"accept"=>["application/xml"], "user-agent"=>["Recurly/2.4.4; ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]"], "accept-encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "authorization"=>["Basic [FILTERED]"]}
<=== 403 Forbidden (1038.8ms)
{"server"=>["blackhole"], "date"=>["Mon, 20 Jul 2015 22:47:52 GMT"], "content-type"=>["text/html"], "content-length"=>["162"], "connection"=>["close"]}
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
```
Recurly::API::Forbidden: /home/deploy/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:340:in `pull_event': Missing end tag for 'hr' (got "body") (REXML::ParseException)
Line: 6
Position: 153
Last 80 unconsumed characters:

from /home/someuser/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:184:in `pull'
from /home/someuser/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rexml/parsers/treeparser.rb:22:in `parse'
from /home/someuser/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rexml/document.rb:287:in `build'
from /home/someuser/.rubies/ruby-2.2.2/lib/ruby/2.2.0/rexml/document.rb:44:in `initialize'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/xml/rexml.rb:7:in `new'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/xml/rexml.rb:7:in `initialize'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/xml.rb:55:in `initialize'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/api/errors.rb:49:in `new'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/api/errors.rb:49:in `xml'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/api/errors.rb:34:in `description'
from /home/someuser/apps/someapp/shared/bundle/ruby/2.2.0/gems/recurly-2.4.4/lib/recurly/api/errors.rb:19:in `to_s'
```

I can't tell how that account was created (we are just receiving and processing webhooks for other companies), but I think if it is possible to have such accounts, it also should be possible to retrieve them.

I've also tried `url`-escaping the dot with %2E in `curl`:
```
curl -H 'Accept: application/xml' \
     -H 'Content-Type: application/xml; charset=utf-8' \
     -u [API key]: 'https://[subdomain].recurly.com/v2/accounts/%2Esome-account
```
but got the same output with `HTTP/1.1 403 Forbidden`

**Comment by bhelx** [comment]
@ivanovv This appears to be a bug at our balancer / routing layer. I am filing a ticket and I'll update you here on the progress. Thanks a lot for pointing it out!

**Comment by bhelx** [comment]
@ivanovv we've decided that we would like to resolve this by adding a validation to prevent account codes that start with dots. Is that going to be a problem for you?

**Comment by ivanovv** [comment]
@bhelx like I said, we are handling data for our customers, so we don't create accounts - only fetch them.
Do I understand you right - no solution for existing account codes, and we have to contact our customers so that they in turn contact Recurly support to migrate those account codes?

**Comment by bhelx** [comment]
@ivanovv Yes, unfortunately the only way forward is to have your merchants fix this account code. This is our mistake for not validating on this sooner. I checked the database and there are only a couple accounts across the system that will need to be changed but we can't do so automatically without risking getting out of sync with the merchant's database. We can reach out to the merchants for you if you want to send me a list of accounts that are causing you problems. My email is ben@recurly.com

**Comment by ivanovv** [comment]
@bhelx thanks a lot, I think the best way for us is to contact the interested parties, and suggest them to fix their data by contacting Recurly support.

Thanks again for cooperation!

**Comment by bhelx** [comment]
Thanks @ivanovv

We should be able to clear it up for them quick

**Comment by bhelx** [comment]
For @ivanovv or anyone finding this. We have implemented the validation and added it to the docs:

```This code may only contain the following characters: [a-z 0-9 @ - _ .] but it may not begin with a dot character```

https://dev.recurly.com/docs/create-an-account
