### ISSUE TITLE
Cannot update subscription add-ons

### ISSUE THREAD

**Issue by jakolehm** [recurly/recurly-client-ruby#203]
It seems that `subscription.update_attributes` does not send `subscription_add_ons` array to api. Tried to update add-ons like this:

```ruby
subscription = Recurly::Subscription.find(subscription_id)
add_on = Recurly::SubscriptionAddOn.new("my-add-on")
add_on.quantity = 1
subscription.subscription_add_ons << add_on
subscription.update_attributes(:timeframe => 'renewal')

subscription = Recurly::Subscription.find(subscription_id)
puts subscription.subscription_add_ons
=> []
```

**Comment by bhelx** [comment]
@jakolehm this is a strange quirk. If you run this:

```ruby
subscription = Recurly::Subscription.find(subscription_id)
add_on = Recurly::SubscriptionAddOn.new("my-add-on")
add_on.quantity = 1
subscription.subscription_add_ons << add_on
subscription.update_attributes(:timeframe => 'renewal')

puts subscription.subscription_add_ons.inspect
```

You'll see that your addons are empty before you are submitting.

The documentation suggests using this syntax:

```ruby
subscription.subscription_add_ons = subscription.subscription_add_ons + [ newaddon ]
```

which does work. The code also suggests you can do this:

```ruby
subscription.add_ons << add_on
```

Which appears to work but I'm not sure why. I'm going to file another issue to figure this out and either make your scenario work or explain this quirk in the documentation.
