### ISSUE TITLE
Use of << on add_ons does not work as expected

### ISSUE THREAD

**Issue by bhelx** [recurly/recurly-client-ruby#220]
Follow up from https://github.com/recurly/recurly-client-ruby/issues/203

The culprit seems to be some old code that was not updated:

https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/subscription/add_ons.rb#L20

Reported by @jakolehm

**Comment by aaron-suarez** [comment]
This issue will be very hard, if not completely impossible to solve. Added a [documentation note](https://dev.recurly.com/v2.15/page/ruby#special-notes) so that users will know not to use the `<<` syntax in that scenario.

Feel free to keep the conversation going here.
