### ISSUE TITLE
Error updating account email: The provided XML was invalid. Unacceptable tag <redemptions>

### ISSUE THREAD

**Issue by vivanov26** [recurly/recurly-client-ruby#222]
Gem version: 2.4.8

Steps to reproduce:

```
a = Recurly::Account.find 'xxxx-xxxx-xxxx'
a.email = 'changed' + a.email
a.save
```

Exception stack trace:

```
E, [2015-11-06T03:07:49.769867 #14575] ERROR -- : The provided XML was invalid. Unacceptable tag <redemptions> (Recurly::API::BadRequest)
/usr/local/rvm/gems/ruby-2.0.0-p481/gems/recurly-2.4.8/lib/recurly/api/net_http_adapter.rb:100:in `request'
/usr/local/rvm/gems/ruby-2.0.0-p481/gems/recurly-2.4.8/lib/recurly/api.rb:64:in `put'
/usr/local/rvm/gems/ruby-2.0.0-p481/gems/recurly-2.4.8/lib/recurly/resource.rb:792:in `save'
/var/uuportal/prod-portal.unblock-us.com/2015-11-03_20-20-58/app/services/recurly_billing_service.rb:311:in `set_account_email'
.....
```

**Comment by alexz70** [comment]
![email update](https://cloud.githubusercontent.com/assets/11528043/10999575/d8df9f90-846a-11e5-8f0f-6270f8e80419.jpg)

**Comment by vivanov26** [comment]
Just to clarify, it seems that ```<redemptions/>``` element gets included into the XML PUT request when updating email value. Here's an example from our production log:

```
<account><account_code>xxxxx</account_code><email>xxxxx@xxxxx.xx</email><redemptions/></account>
```

**Comment by csmb** [comment]
Hi there @vivanov26. I can't seem to reproduce this locally.

When I try to reproduce, the XML sent over is:

```
<?xml version="1.0"?>
<account>
  <account_code>my_account</account_code>
  <email>changedmy_account@email.com</email>
</account>
```

Is there anything special about the account that you're trying to update, or does this happen on each account? Any extra info you've got would be great!

**Comment by vivanov26** [comment]
Hi @csmb, thanks for looking into this. This may be related to our Recurly account. To answer your earlier question, yes it happens for every user account.

I think I figured out the additional step that needs to be done to reproduce this error: invoke
```
a.redemptions
```
before 
```
a.save
```

I will send the full trace to @rachelquick as I don't want to share our test account API key in this GitHub ticket.

**Comment by csmb** [comment]
Hey @vivanov26 I'm able to reproduce this invalid XML error when invoking `redemptions`. I'll get to work on a fix and will update you with status, here.

**Comment by vivanov26** [comment]
@csmb thank you

**Comment by csmb** [comment]
Hey there @vivanov26, we've got a [PR for the changes](https://github.com/recurly/recurly-client-ruby/pull/223). We should get it merged in and will cut a new release next week, and you'll see the release noted in this thread!

**Comment by vivanov26** [comment]
@csmb great, thanks for the update

**Comment by bhelx** [comment]
This was merged with https://github.com/recurly/recurly-client-ruby/pull/223 and went into 2.4.9 https://github.com/recurly/recurly-client-ruby/pull/225

Please reopen if there are issues.
