### ISSUE TITLE
Autoloading and Rails

### ISSUE THREAD

**Issue by pmorton** [recurly/recurly-client-ruby#235]
We are getting some strange exceptions from the recurly railtie each time we deploy our application. The app is rails 4.2 with puma running with 2 clustered mode workers with 16 threads. When the application is deployed the first call into our app (any controller) will trigger the following exception: ```NoMethodError: undefined method `accept_language=' for Recurly::API:Class``` and a massive stack trace in what looks like the request filter phase. This generally does not make sense because the method is defined. After much research, it seems that this is _probably_ an issue with the use of autoload. 

https://bugs.ruby-lang.org/issues/921 confirms that for 1.9.3 and older, autoload is not thread safe while 2.x is. Further @headius seems to indicate that autoload is only thread safe is the same autoload mechanism is used across the board. https://github.com/headius/thread_safe/issues/15#issuecomment-28929979. So here is where I believe that issue to be: Rails uses it's own autoloading systems, while this gem uses another. There is some race condition that is causing the ```Recurly::API``` class to only be partially loaded when it is called. 

To address this issue we could take one of a couple of approaches

1. Dump autoloading and use require. This would make the gem slower to load, but this should be trivial since the gem is pretty small.

2. Hook into the rails autoloading system. Each file using autoloads would add the following to the class
```extend ActiveSupport::Autoload if defined?(ActiveSupport::Autoload)```. The net result is that the activesupport autoloader which is used by rails would also be used by this gem. Doing this would allow lazy loading for ruby files in development and eager loading in production.

I believe that 1 is the simplest with very little performance tradeoff, but if load performance is important to you option 2 would work as well.  Let me know what you think. I am happy to code this up.

**Comment by pmorton** [comment]
Good Monday @bhelx Let me know your thoughts on the above and I would be happy to get this moving.

**Comment by bhelx** [comment]
Thanks @pmorton

Will be taking a look today

**Comment by bhelx** [comment]
@pmorton 

Okay, from what I can tell, our Railtie is pretty old and this library was written when using threaded servers was less common. So it's no wonder there are some issues.

At first glance I would definitely say I want to dump autoload (option 1). I find messing with ruby's requires to be a little to opaque and I never liked that this library adopted autoload. I also agree that the performance penalty will be negligible. I'd be happy to look over your PR or help you get it working.

**Comment by pmorton** [comment]
Great. I will get this moving. Cheers!

**Comment by bhelx** [comment]
Closed with https://github.com/recurly/recurly-client-ruby/issues/236

Thanks @pmorton
