### ISSUE TITLE
Update the address for an account?

### ISSUE THREAD

**Issue by cionescu** [recurly/recurly-client-ruby#247]
I am having issues updating the address for a Recurly Account. 

```ruby
$ a = Recurly::Account.find("[account-code]")
===> GET https://caring.recurly.com/v2/accounts/[account-code]
...
<=== 200 OK (216.6ms)
...
$ a.address
=> #<Recurly::Address address1: "330 Blah", address2: "Flat 506", city: "San Francisco", country: nil, phone: "4159365945", state: "CA", zip: "94158">
$ a.address.address1 = "New Address"
$ a.address.changed?
=> true
$ a.changed?
=> false
```

Then, if I try to save the account it doesn't make a request to recurly. Completely unrelated, but if I try to save the address I get a 404

```ruby
$  a.address.save
===> POST https://caring.recurly.com/v2/address
<=== 404 Not Found (589.4ms)
<errors>
  <error>No route matches [POST] "/v2/address"</error>
</errors>
```

Can you please let me know what's wrong with my approach?

**Comment by drewish** [comment]
Does `a.save` work any better?

**Comment by cionescu** [comment]
`a.save` returns true. But I would expect it to make a PUT request to recurly to update the account.

**Comment by drewish** [comment]
does it update the account though?

**Comment by cionescu** [comment]
No, it doesn't

**Comment by bhelx** [comment]
I think the problem is that `account.changed?` is probably still false. Let me check this and confirm that this is a bug.

**Comment by bhelx** [comment]
This doesn't look correct

```ruby
puts "address changed: #{account.address.changed?}"      #=> true
puts "address changed: #{account.address_changed?}"     #=> false
puts "changed attributes: #{account.changed_attributes}"   #=> {}
```

**Comment by bhelx** [comment]
This is a quick fix: https://github.com/recurly/recurly-client-ruby/pull/248

But it's probably not the best solution moving forward. We're going to need to discuss how to better address this problem of `changed_attributes` with nested objects.

**Comment by cionescu** [comment]
Thank you! And thanks for responding so quickly 😄

**Comment by bhelx** [comment]
@cionescu Sure thing. I'm going to do a deeper dive tomorrow.

**Comment by bhelx** [comment]
Closed with https://github.com/recurly/recurly-client-ruby/pull/248

Will go into release tomorrow
