### ISSUE TITLE
Handle WebHook Events

### ISSUE THREAD

**Issue by brauliobo** [recurly/recurly-client-ruby#265]
Hi, first of all, thanks for this gem!

Can this gem parse the webhooks events into nice ruby objects?

**Comment by bhelx** [comment]
@brauliobo It's not a very well documented feature, but we did have someone contribute webhooks unmarshalling code: https://github.com/recurly/recurly-client-ruby/pull/217/files

Let me know if you have questions understanding how to use it.

**Comment by brauliobo** [comment]
nice @bhelx, will try it tomorrow!
