### ISSUE TITLE
Coupon redemptions produce unusable errors

### ISSUE THREAD

**Issue by sdhull** [recurly/recurly-client-ruby#270]
My expectation is that I should be able to `rescue Recurly::Error => e` and then do `e.to_s` to get a customer-facing error message. Is this correct or no?

```ruby
[7] pry(main)> begin
[7] pry(main)*   redemption = coupon.redeem! org.recurly_id
[7] pry(main)* rescue => e
[7] pry(main)*   err = e
[7] pry(main)* end
=> Recurly::Resource::Invalid
[8] pry(main)> err.to_s
=> ""
[9] pry(main)> err.record
=> #<Recurly::Coupon applies_for_months: nil, applies_to_all_plans: true, applies_to_non_plan_charges: false, coupon_code: "free-99", coupon_type: "single_code", created_at: Fri, 14 Oct 2016 00:50:13 +0000, description: "Free ninety-nine!!!!! $99 credit", discount_in_cents: #<Recurly::Money USD: 99_00>, discount_percent: nil, discount_type: "dollars", duration: "forever", free_trial_amount: nil, free_trial_unit: nil, invoice_description: "Free ninety-nine!!!!! $99 credit", max_redemptions: nil, max_redemptions_per_account: 1, name: "Account Coupon Test", plan_codes: [], redeem_by_date: nil, redemption_resource: "account", single_use: false, state: "redeemable", temporal_amount: nil, temporal_unit: nil, unique_template_code: nil>
[10] pry(main)> err.record.errors
=> {}
```

Meanwhile, if I build the Redemption manually as it's done in the `#redeem!` method,
```ruby
[23] pry(#<Recurly::Coupon>):1> begin
[23] pry(#<Recurly::Coupon>):1*   Recurly::Redemption.from_response follow_link(:redeem,
[23] pry(#<Recurly::Coupon>):1*     :body => redemption.to_xml
[23] pry(#<Recurly::Coupon>):1*   )
[23] pry(#<Recurly::Coupon>):1* rescue => e
[23] pry(#<Recurly::Coupon>):1*   err = e
[23] pry(#<Recurly::Coupon>):1* end
...
[26] pry(#<Recurly::Coupon>):1> puts e.response.body
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error field="coupon.base" symbol="maxed_out_for_account">Coupon has reached max redemptions for this account</error>
</errors>
```

So a useful error _is_ returned by the API, it's simply inaccessible if you use the `#redeem!` method.

**Comment by bhelx** [comment]
Thanks a bunch for reporting! This is indeed a bug. I'll check your PR now.

**Comment by bhelx** [comment]
Also, I wanted to address this question:

> My expectation is that I should be able to rescue Recurly::Error => e and then do e.to_s to get a customer-facing error message. Is this correct or no?

It depends on what kind of error you are looking for. If you are accepting user input of some sort, you want to try to catch a validation error first then fall back to a more general error. The validation errors will either give you a specific field that has a problem, or it will use the keyword "base" to mean that the problem is with the state of the resource and not a specific field in your change data.

It's best to work with the map of returned errors:

```ruby
begin
  coupon.redeem!(account_code)
rescue Recurly::Resource::Invalid => e
  puts e.record.errors #=> {"base"=>["Coupon has reached max redemptions for this account"]}
end
```

**Comment by sdhull** [comment]
We're using the Recurly js to take billing info and get a token back, but we have a single endpoint where our customers submit a form which triggers some Recurly API calls (the calls may be different depending on what the customer is doing). I want a thematic error message to show if something goes wrong (eg, did adding billing info token fail? did creating the subscription fail? did the transaction fail? did coupon code lookup fail? did coupon redemption fail?). Beyond that, I will consider field-level errors when appropriate, however first and foremost I want a thematic error message that explains what went wrong. Something better than "We couldn't process your request" or similar generic messages.
