### ISSUE TITLE
Subscription Add Ons Usage

### ISSUE THREAD

**Issue by Kinertia** [recurly/recurly-client-ruby#272]
When getting the usage on a subscription add-on it doesn't give you the ID for the usage in the response (although you can see it in the logs). Other than saving the ID to your db when it's created there's no way to get the ID of the usage from the API, which makes it impossible using this library to update or delete a usage.

**Comment by bhelx** [comment]
@Kinertia You should be able to call `update` and `destroy` on usage objects like any other objects. If there is some other way you wish to use it, I'd be happy to alter the library to help. Could you maybe provide some example code of what you are trying to accomplish and how you want it to work?

**Comment by Kinertia** [comment]
@bhelx This is the code I have and in the response I'm not seeing the usage id. But I need to give the id if I want to delete a certain usage record.

`recurly_subscription = Recurly::Subscription.find(leadgen_subscriptions.last.recurly_subscription_id)
				
				sub_add_on = recurly_subscription.subscription_add_ons.detect do |add_on|
					add_on.add_on_code == 'leadgen_leads'
				end

				usage_recorded = sub_add_on.usage.paginate({start_datetime: DateTime.now.beginning_of_month, end_datetime: DateTime.now.end_of_month})`


How can I delete a usage_recorded for this month using this library?

**Comment by bhelx** [comment]
Well, like i said before, you can call `destroy` on any resource that is destroyable. In your case, since you are getting a page of items, you'll want to iterate through them. Something like this maybe:

```ruby
usage_recorded.each do |usage|
  if usage.destroy
    # it was destroyed
  else
    # some error happened
  end
end
```

**Comment by spq24** [comment]
thanks I will give it a try. Still a bit weird that you can't easily get the usage id.

**Comment by bhelx** [comment]
@spq24 You shouldn't need it just to delete, but we are adding it into the response in the next release because you may need it for other purposes. I'm going to ping back here when it's released.

**Comment by spq24** [comment]
Yup I am going to test that out today but in general I think your right and it makes sense, just wasn't intuitive looking at the api docs it says you need the ID to delete something but I didn't see how to do it with the library, that's where my confusion was. I appreciate your help on this to get it working and for taking care of the library

**Comment by bhelx** [comment]
@spq24 Sure thing, any time. I've got some better library specific documentation in the works.

**Comment by bhelx** [comment]
@spq24 @Kinertia we went ahead and added this id field https://github.com/recurly/recurly-client-ruby/pull/288
