### ISSUE TITLE
"SystemStackError: stack level too deep" when calling "as_json" on Recurly::Account object

### ISSUE THREAD

**Issue by vrul** [recurly/recurly-client-ruby#274]
Hi guys, we are getting `SystemStackError` when trying to call method `as_json` on `Recurly::Account` object, eg
```
Recurly::Account.find('development_user_1').as_json
```
The server log is next:
```
Started GET "/" for IP at 2016-10-24 14:59:23 +0000
Processing by HomeController#show as HTML
===> GET https://api.recurly.com/v2/accounts/production_user_id
<=== 200 OK (404.8ms)
===> GET https://api.recurly.com/v2/accounts/production_user_id/subscriptions
<=== 200 OK (158.4ms)
===> GET https://api.recurly.com/v2/accounts/production_user_id/adjustments
<=== 200 OK (422.9ms)
Completed 500 Internal Server Error in 1415ms (ActiveRecord: 14.1ms)
** [Airbrake] Success: Net::HTTPOK

SystemStackError (stack level too deep):
  newrelic_rpm (3.15.0.314) lib/new_relic/agent/instrumentation/middleware_tracing.rb:106
```
Is this something to do with API on your side? Please, let us know if you need further info

Some environment info:
```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
$ rails -v
Rails 4.2.7.1
$ bundle show recurly
/home/ubuntu/.rvm/gems/ruby-2.1.2@xxx/bundler/gems/recurly-client-ruby-d63f1f2dce72
```

**Comment by bhelx** [comment]
@vrul I think `as_json` is something that rails puts on the objects. We don't control it. It looks like it's trying to walk through all the attributes and call them. If you are trying to get json, you may want to write a more explicit serializer. You could also try serializing the attributes hash:

```ruby
account = Recurly::Account.find('development_user_1')
account.attributes.as_json
```

**Comment by bhelx** [comment]
@vrul It seems like the ultimate problem is when it tries to serialize a `Pager`. If you want a quick fix you can override it's as_json and put something sensible.

```ruby
class Recurly::Resource::Pager
  def as_json
    nil
  end
end
```

I'll need to think about how we should handle this in the library.

**Comment by vrul** [comment]
@bhelx thank you for fast reply
so in my case I'm serializing a `Recurly::Subscription` object. I have next attributes on it:
```
> recurly_subscription.attributes
=> {"currency"=>"GBP",
 "text"=>"\n  ",
 "plan"=>
  #<Recurly::Plan accounting_code: nil, bypass_hosted_confirmation: nil, cancel_url: nil, created_at: nil, description: nil, display_donation_amounts: nil, display_phone_number: nil, display_quantity: nil, name: "Name", payment_page_css: nil, payment_page_tos_link: nil, plan_code: "plan_code", plan_interval_length: nil, plan_interval_unit: nil, setup_fee_in_cents: nil, success_url: nil, tax_exempt: nil, total_billing_cycles: nil, trial_interval_length: nil, trial_interval_unit: nil, unit_amount_in_cents: nil, unit_name: nil>,
 "uuid"=>"uuid",
 "state"=>"active",
 "unit_amount_in_cents"=>100,
 "quantity"=>1,
 "activated_at"=>Tue, 30 Sep 2014 17:05:12 +0000,
 "canceled_at"=>nil,
 "expires_at"=>nil,
 "total_billing_cycles"=>nil,
 "remaining_billing_cycles"=>nil,
 "current_period_started_at"=>Fri, 14 Oct 2016 17:05:12 +0000,
 "current_period_ends_at"=>Sat, 14 Oct 2017 17:05:12 +0000,
 "trial_started_at"=>Tue, 30 Sep 2014 17:05:12 +0000,
 "trial_ends_at"=>Tue, 14 Oct 2014 17:05:12 +0000,
 "terms_and_conditions"=>nil,
 "customer_notes"=>nil,
 "po_number"=>nil,
 "net_terms"=>0,
 "collection_method"=>"automatic",
 "subscription_add_ons"=>[],
 "account"=>
  #<Recurly::Account accept_language: "ru-RU,ru;q=0.8,uk;q=0.6,en-US;q=0.4,en;q=0.2", account_code: "development_user_1", address: #<Recurly::Address address1: "", address2: "", city: "", country: "", phone: "", state: "", zip: "">, company_name: "", created_at: Tue, 30 Sep 2014 14:15:12 +0000, email: "email@example.com", first_name: "FirstName", hosted_login_token: "hosted_login_token", last_name: "LastName", state: "active", tax_exempt: nil, username: "", vat_number: "">}
```
and the described problem appears when I call `recurly_subscription.attributes.as_json` so that it walks through all the subscription's attributes (as you've mentioned before), successfully serializes `Recurly::Plan` object but fails on serializing `Recurly::Account` as I noticed above. For now what we have done is we've called `.except('account')` on `recurly_subscription.attributes` followed by calling method `.as_json` which allowed us to avoid a noticed error, however it looked more like a "hack" than a clear solution and what we strive to do is we strive to come up with a clear one. That's why I've posted this issue

**Comment by vrul** [comment]
just wondering why it fails only on `Recurly::Account`, not on `Recurly::Plan` objects?

**Comment by drewish** [comment]
My suspicion would be the number of relations since the plan's only relation is the add-ons but accounts would have subscriptions, invoices, transactions, coupons, etc

**Comment by bhelx** [comment]
hey @vrul

Which version of the library are you on? i've loaded up a new rails project with the latest version of this library `2.7.5` and can't seem to reproduce this anymore. Also tried this script:

```ruby
require 'active_support'
require 'active_support/all'

sub = Recurly::Subscription.find('3a5ecd779a5d02c21cec8d4b139d4c7b')
puts sub.attributes.as_json
```

I want to get a resolution for this in place. Let me know if you are still having the problem or can help me reproduce.

**Comment by danhunter** [comment]
hey @bhelx 

I'm able to reproduce this with an instance of `Recurly::Account` using version `2.7.5`

**Comment by bhelx** [comment]
@danhunter I see, I forgot that this is just applying to `Account` right now

**Comment by bhelx** [comment]
Okay, I think #295 solves the explosion at least. But I'll need to figure out how I can get it to not call remote links. I'll also need to figure out if we want to just keep ignoring the options Hash or respect what rails wants us to do.

**Comment by danhunter** [comment]
Ah ok, thanks @bhelx

**Comment by bhelx** [comment]
Since this is causing problems for some people, I'm going to do a small release today with this change included.
