### ISSUE TITLE
Recurly::Webhook::NotificationError: 'NewDunningEventNotification' is not a recognized notification

### ISSUE THREAD

**Issue by brauliobo** [recurly/recurly-client-ruby#280]
Receiving this error while using `Recurly::Webhook.parse`

**Comment by bhelx** [comment]
Hey @brauliobo, this will be address by #277

**Comment by brauliobo** [comment]
ok, waiting for its merge!

**Comment by bhelx** [comment]
Closing with https://github.com/recurly/recurly-client-ruby/pull/277

This will be released today in `2.7.4` https://github.com/recurly/recurly-client-ruby/pull/282
