### ISSUE TITLE
No timeframe attribute on subscription change

### ISSUE THREAD

**Issue by brauliobo** [recurly/recurly-client-ruby#281]
How can I set the timeframe attribute as in the docs: https://dev.recurly.com/docs/preview-subscription-change

**Comment by brauliobo** [comment]
An workaround is to set using `[]`: `subscription[:timeframe] = 'renewal'`

**Comment by drewish** [comment]
I think that is the solution rather than a workaround, unless I'm misunderstanding what you're asking for.

**Comment by bhelx** [comment]
@brauliobo it should be an attribute that you can set:

```ruby
subscription.timeframe = 'renewal'
```

If it's not, that may be an oversight on our part. I am checking now.

**Comment by bhelx** [comment]
@brauliobo There are two ways to do subscription previews, one is previewing a new subscription in which case you use the class method Subscription#preview:

```ruby
subscription = Subscription.preview(
  plan_code: 'plan_code',
  currency: 'USD',
  account: {
    account_code: 'account_code',
  }
)
```

The other is previewing a subscription change (which I assume is what you want by your link). Which involves modifying the subscription and calling the #preview instance method:

```ruby
subscription = Subscription.find 'abcdef1234567890'
subscription.quantity = 5
subscription.preview
```

It does seem like `timeframe` should be a writeable attribute so I'll add it now and get it into the 2.7.4 release which is going out today https://github.com/recurly/recurly-client-ruby/pull/282

**Comment by brauliobo** [comment]
thanks @bhelx, I was missing the method :)

**Comment by bhelx** [comment]
@brauliobo no problem, thanks for reporting. Feel free to post any other questions or problems!
