### ISSUE TITLE
Subscription Preview Response

### ISSUE THREAD

**Issue by jaypandya73** [recurly/recurly-client-ruby#294]
``subscription = Recurly::Subscription.find(uuid)``
``subscription.plan_code = new_plan_code``
``subscription.preview``

When I try to get preview of subscription from above code  It is giving me response of ```Recurly::Subscription``` class. 

I want response in __XML__ as it shown in Recurly Documentation.
https://dev.recurly.com/docs/preview-subscription

 So i can extract information from it.

Your help is appreciated. Thanks!!!!

**Comment by bhelx** [comment]
Hey @jaypandya73 

If you run something like this:

```ruby
subscription = Recurly::Subscription.find(uuid)

puts subscription.inspect

subscription.plan_code = '93f2e12f6a'
subscription.quantity = 1
subscription.preview

puts subscription.inspect
```

You'll see that the subscription object has been changed with the new attributes as if the change was applied.

**Comment by jay-pandya-btc** [comment]
@bhelx - Yeah...I tried that and ``subscription.inspect`` helped me actually to extract exact info.
Though i actually needed response in  __XML__. But i figured out way.

Thanks for your help. Really appreciate it.

**Comment by jaypandya73** [comment]
@bhelx - Yeah...I tried that and subscription.inspect helped me actually to extract exact info.
Though i actually needed response in XML. But i figured out way.

Thanks for your help. Really appreciate it.

**Comment by bhelx** [comment]
@jaypandya73 sure thing. we don't officially support getting the xml but glad you found a way to do so. If you have any other questions, would be glad to help.
