### ISSUE TITLE
Question about webhooks

### ISSUE THREAD

**Issue by victorhazbun** [recurly/recurly-client-ruby#306]
I'm using the Recurly hosted payments pages. And I'm wondering if it is a good idea to use the  new_subscription_notification webhook to tell my application that now an account have a subscription so the user owner of the account can use the paid application features? Whats your advice?

**Comment by bhelx** [comment]
Essentially what you are trying to do is synchronize state. It will work, but we advise against relying the webhooks as a mechanism to synchronize state b/w your database and recurly. What does your signup flow look like? Where do your users create subscriptions? Are you using a recurly.js form? You usually want to activate their features after your server sends the request to generate a subscription.

**Comment by bhelx** [comment]
@victorhazbun does that answer your question? Gonna close this for now. Feel free to open if you think there is something unresolved.
