### ISSUE TITLE
Dependency Nokogiri version 1.6 causing warnings.

### ISSUE THREAD

**Issue by akaKuruma** [recurly/recurly-client-ruby#308]
Nokogiri version 1.6 is using Fixnum which is deprecated on the Ruby version 2.4. 
This is causing warnings: 
`/ruby-2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/html/document.rb:164: warning: constant ::Fixnum is deprecated`

**Comment by bhelx** [comment]
Hey @akaKuruma Thanks for letting us know. I'm only just now getting the specs to run on 2.4 #314. I'll need to look into which versions of nokogiri we can support. Currently what is holding us back is we still need to support ruby 1.9.3. Do you have any recommendations?

**Comment by akaKuruma** [comment]
@bhelx, I believe this is solved in the [Master branch](https://github.com/recurly/recurly-client-ruby/blob/master/recurly.gemspec#L26). Thank you! =)

**Comment by bhelx** [comment]
@akaKuruma Thanks for reporting!
