### ISSUE TITLE
Upgrade Nokogiri To 1.7.1

### ISSUE THREAD

**Issue by smythey21** [recurly/recurly-client-ruby#316]
The current version of `nokogiri` this gem is using has [known vulnerabilities](https://github.com/sparklemotion/nokogiri/issues/1615). Can we update to 1.7.1?

**Comment by bhelx** [comment]
Thanks @smythey21. I'm looking into it now. I'm currently held back by having to continue support for ruby 1.9.3 though I may find a way around that.

**Comment by bhelx** [comment]
Okay, unfortunately I still can't drop support for 1.9 and 2.0 even though they were EOL'd in 2015 and 2016 respectively. I do think, however, I can deprecate them. I'm going to try to upgrade the nokogiri version and force people on those deprecated rubies to use the rexml adapter.

**Comment by bhelx** [comment]
I'll have a new release for this when I get time. Will likely be `2.9.0` since it has breaking changes to dependencies.

**Comment by smythey21** [comment]
Thanks @bhelx! Looking forward to that :)
