### ISSUE TITLE
Webhook properties are missing

### ISSUE THREAD

**Issue by jschwendt** [recurly/recurly-client-ruby#336]
It appears that certain webhook properties are missing from the models.  For example, if I try to access a parsed webhook object and attempt to consume the account.phone property, I get an error that the phone property does not exist on the account object.  Yet, if I inspect the body of the webhook, I find that it includes the phone property.  I'm using API version 2.7 and gem version 2.10.1 which seems to indicate compatibility from the release notes.  There are other missing webhook properties as well, but I think it's better to review everything.

**Comment by bhelx** [comment]
@jschwendt I believe the webhooks and the regular API models use the same parser so they should be up to date. I don't think there is an `Account#phone` property. I think you need to get the phone number from the BillingInfo or the Address. You'll probably need to decide which to use because these can be different.

Could you post an example of any other properties you are having trouble with? Posting the xml in the webhook would be helpful too.

**Comment by bhelx** [comment]
@jschwendt My mistake. I'm seeing that the webhook contains the phone property but our API does not. I know there are probably still some inconsistencies here because the xml is not exactly 1x1. If you could, please still let me know of any properties fields you have found.

**Comment by jschwendt** [comment]
Of the ones I'm consuming thus far, the only other one I'm running into is subscription.total_amount_in_cents.

Thanks for jumping on this!

**Comment by jschwendt** [comment]
A few more in transaction:
date
gateway
gateway_error_codes
invoice_number

**Comment by ananova** [comment]
Using release 2.16.0.

This has become a problem for us about a week ago.  We were relying on some invoice properties in [dunning event notifications](https://dev.recurly.com/page/webhooks#dunning-event-notifications) that no longer exist.

API properties:
- attempt_next_collection_at
- balance_in_cents
- closed_at
- collection_method
- created_at
- credit_payments
- currency
- customer_notes
- discount_in_cents
- due_on
- invoice_number
- invoice_number_prefix
- line_items
- net_terms
- origin
- po_number
- recovery_reason
- refundable_total_in_cents
- state
- subtotal_before_discount_in_cents
- subtotal_in_cents
- tax_in_cents
- terms_and_conditions
- total_in_cents
- transactions
- type
- updated_at
- uuid
- vat_number

(old) Webhook properties:
- closed_at
- collection_method
- currency
- date
- due_at
- dunning_events_count
- final_dunning_event
- invoice_number
- invoice_number_prefix
- net_terms
- po_number
- state
- subscription_id
- subscription_ids
- total_in_cents
- uuid
- vat_number

What's missing:
- date
- due_at
- dunning_events_count
- final_dunning_event
- subscription_id
- subscription_ids

What was added:
- attempt_next_collection_at
- balance_in_cents
- created_at
- credit_payments
- customer_notes
- discount_in_cents
- due_on
- line_items
- origin
- recovery_reason
- refundable_total_in_cents
- subtotal_before_discount_in_cents
- subtotal_in_cents
- tax_in_cents
- terms_and_conditions
- transactions
- type
- updated_at

We were using
- due_at
- dunning_events_count

The webhook xml for invoice in the dunning event notification does not match the API either.

dunning event notification xml for invoice:
- balance_in_cents
- closed_at
- collection_method
- created_at
- currency
- customer_notes
- discount_in_cents
- due_on
- dunning_events_count
- final_dunning_event
- invoice_number
- invoice_number_prefix
- net_terms
- origin
- po_number
- state
- subscription_ids
- subtotal_before_discount_in_cents
- subtotal_in_cents
- tax_in_cents
- terms_and_conditions
- total_in_cents
- updated_at
- uuid
- vat_number

```diff
diff -u webhook.txt api.txt
--- webhook.txt	2018-10-01 15:57:54.000000000 -0500
+++ api.txt	2018-10-01 16:01:32.000000000 -0500
@@ -1,26 +1,36 @@
+amount_remaining_in_cents
+attempt_next_collection_at
 balance_in_cents
 closed_at
 collection_method
 created_at
+credit_customer_notes
 currency
 customer_notes
 discount_in_cents
 due_on
-dunning_events_count
-final_dunning_event
 invoice_number
 invoice_number_prefix
+line_items
 net_terms
 origin
 po_number
+recovery_reason
+refund_geo_code
+refund_method
+refund_tax_date
 state
-subscription_ids
 subtotal_before_discount_in_cents
 subtotal_in_cents
 tax_in_cents
+tax_rate
+tax_region
+tax_type
+tax_types
 terms_and_conditions
 total_in_cents
+transactions
+type
 updated_at
 uuid
 vat_number
```

**Comment by aaron-suarez** [comment]
@jschwendt @ananova If you would like to take a look at #422 and let me know if I may have missed anything, please feel free. There were a lot of properties missing and I believe I've got them all, but more eyes will always help.

Thanks in advance!
