### ISSUE TITLE
Currency now required on Subscriptions

### ISSUE THREAD

**Issue by zmbc** [recurly/recurly-client-ruby#338]
Just upgraded this gem from `2.10.0` to `2.10.1` and noticed a breaking change. It looks like Subscription now requires `currency` to be set, which it didn't used to. Digging into the git diff, I saw that your tests were updated to reflect the new requirement:

https://github.com/recurly/recurly-client-ruby/pull/332/commits/cc0ab3d8ef95f5ea1141963159170d18c109dbcb#diff-ff60beda18ec7ceacc17a6833d6dd2a5

Would be nice to put this in the changelog.

**Comment by bhelx** [comment]
@zmbc This should not be the case and is perhaps a mistake on our part. I'll test, fix, and publish as `2.10.2` if so.

**Comment by bhelx** [comment]
@zmbc Could you try #339 ?

I've decided to add a temporary fix in the `purchases` code so we can honor the contract. The next minor bump will contain the breaking changes we intended.

**Comment by bhelx** [comment]
We've releases `2.10.2` with the fix. We recommend everyone on `2.10.1` upgrade to that. https://github.com/recurly/recurly-client-ruby/releases/tag/2.10.2
