### ISSUE TITLE
400 when creating a subscription with a shipping address via Purchases API

### ISSUE THREAD

**Issue by mwoghiren** [recurly/recurly-client-ruby#352]
Hiya!

I'm attempting to create a subscription via the Purchases API.  Everything works great until I specify a `shipping_address` hash on the subscription in the purchase.  The request then results in a 400 response with the following explanation:

> This request cannot be completed using version 2.9 of the API.
> Support for multiple shipping addresses per invoice was added in version 2.10.

Which is fine, although the "multiple" bit is puzzling—I'm specifying only one shipping address. :)

Can someone verify that specifying a shipping address on a subscription created via a purchase is currently unsupported and will soon be supported when the Ruby client uses API version 2.10?  (And is there an ETA on that?)

Thanks!

**Comment by bhelx** [comment]
@mwoghiren It does seem strange, can you paste some example code demonstrating the problem?

**Comment by bhelx** [comment]
Actually, I was able to reproduce:

```ruby
require 'securerandom'

plan = Recurly::Plan.first

p = Recurly::Purchase.new({
  currency: 'USD',
  collection_method: :automatic,
  customer_notes: 'Some notes for the customer.',
  terms_and_conditions: 'Our company terms and conditions.',
  vat_reverse_charge_notes: 'Vat reverse charge notes',
  account: {
    first_name: 'Benjamin',
    last_name: 'Benjamin',
    account_code: SecureRandom.uuid,
    billing_info: {
      first_name: 'Benjamin',
      last_name: 'Du Monde',
      address1: '400 Alabama St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94110',
      country: 'US',
      number: '4111-1111-1111-1111',
      month: 12,
      year: 2019,
    }
  },
  subscriptions: [
    {
      plan_code: plan.plan_code,
      shipping_address: {
        nickname: "Work",
        first_name: "Verena",
        last_name: "Example",
        company: "Recurly Inc.",
        phone: "555-555-5555",
        email: "verena@example.com",
        address1: "400 Alabama St.",
        city: "San Francisco",
        state: "CA",
        zip: "94110",
        country: "US"
      }
    }
  ],
})

begin
  invoice = Recurly::Purchase.invoice!(p)
  require'pry';binding.pry;
rescue Recurly::Resource::Invalid => e
  require'pry';binding.pry;
end
```

I'm going to take a look at this first thing in the morning (CST). I believe the problem is that shipping addresses are not supported for purchases yet, however the error message is confusing so I'll need to check.

**Comment by bhelx** [comment]
I just confirmed that this is not a bug, but a confusing error message. shipping addresses are not supported on purchases yet. This change will be going out in 2.10 which I plan on releasing before (or on) `1/8`. In the mean time, we are going to fix the confusing error message.

**Comment by mwoghiren** [comment]
Thanks for investigating.  We'll add shipping addresses to the subscription manually in the meantime and eagerly anticipate the new release.  Thanks again!

**Comment by bhelx** [comment]
No problem, thanks for your understanding. I'll be sure to link this issue in the release.
