### ISSUE TITLE
Invoice refunds do not return invoice collections

### ISSUE THREAD

**Issue by Sinetheta** [recurly/recurly-client-ruby#362]
Hi, I'm having a little trouble upgrading to 2.14.0

`Recurly::Invoice#refund_amount` is expecting an `<invoice_collection>` as per the stubbed API response here https://github.com/recurly/recurly-client-ruby/blob/master/spec/fixtures/invoices/refund-201.xml

but when I hit that endpoint I get a top level `<invoice>` which blows up when the gem parses it.

```
curl -H 'Accept: application/xml' \
     -H 'X-Api-Version: 2.10' \
     -H 'Content-Type: application/xml; charset=utf-8' \
     -u '[api key]' \
     -d '<invoice><amount_in_cents>25</amount_in_cents><refund_method>transaction_first</refund_method></invoice>' \
    https://[subdomain]/v2/invoices/:invoice_number
```

**Comment by bhelx** [comment]
I took a look at this. It looks to me like refunds were NOT changed to use `InvoiceCollection` and that wasn't updated in the PR. I'll prepare a fixed released for this and link it to this issue. Thanks for pointing this out @Sinetheta
