### ISSUE TITLE
Changing plan and setting custom unit_amount_in_cents doesn't work as expected.

### ISSUE THREAD

**Issue by nasaabg** [recurly/recurly-client-ruby#368]
I am using version 2.11.3 and I found that kind of issue:

Let's say my current subscription unit_amount_in_cents = 50000 and the catalog price of this plan is $700 and I want to have a new plan but with the same amount $500
I try to change the plan_code and want to have unit_amount_in_cents also 50000
I have the following code:

```ruby
recurly_subscription.plan_code = "new_plan_code"
recurly_subscription.unit_amount_in_cents = 50000
recurly_subscription.save!
```

It doesn't work for me. I expect to have an updated subscription in Recurly with the new plan and not changed the amount ($500). What I receive is a subscription to a correct plan, but with the incorrect amount. The amount is set to a catalog price of my new plan.

What I find out digging with `pry` locally to your gem is that when I change the plan_code of the subscription and I set the unit_amount_in_cents to 50000 it ends up with the XML payload send without the unit_amount_in_cents key. I assume this is why the catalog price is set for my new plan. Moreover, when I change the XML payload just before I make the API call and I add the unit_amount_in_cents key with value 50000 it works as expected and I have a correct subscription in Recurly which means I am able to perform that kind of action via API. 
I assume the issue is with defining `changed_attributes` of Resource. We look only whether the value of specific key has changed not if the developer really called setter method to set this value. 

Can you confirm or deny my assumptions and advise what am I supposed to do?

**Comment by bhelx** [comment]
@nasaabg This is an unfortunate design issue with the active-record style interface. I'd suggest trying the `Resource#update_attributes` method. It seems to work for me:

```ruby
subscription.update_attributes(
  unit_amount_in_cents: 500, 
  plan_code: "new_plan_code"
)
```

**Comment by bhelx** [comment]
@nasaabg Let me know if this is still a problem for you.
