### ISSUE TITLE
Invoice shipping_address has name instead of first and last

### ISSUE THREAD

**Issue by Sinetheta** [recurly/recurly-client-ruby#370]
Why does Lookup Invoice return a payload which includes a `<shipping_address><name>` but no first or last name? eg: https://dev.recurly.com/docs/lookup-invoice-details

This means to get separate first and last names for an invoice we need to look to the current account info, which may have changed since an invoice was generated.

**Comment by bhelx** [comment]
@Sinetheta This looks to me to be a mistake in the documentation. `ShippingAddress` should have both `first_name` and `last_name` https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/shipping_address.rb#L8-L9
as well as a `nickname` https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/shipping_address.rb#L15
Are you seeing this in the actual xml responses or just the documentation?

**Comment by Sinetheta** [comment]
Unfortunately this is accurate. The response contains only the concatenated `<name>` which means that not only is information destroyed but it's not easily accessible because `name` is not a whitelisted attribute.

**Comment by bhelx** [comment]
@Sinetheta definitely seems like a bug or design error. I'm looking into it tomorrow. I'll have some more information then.

**Comment by Sinetheta** [comment]
Any word on this @bhelx ? I understand that at it's core this isn't a question for the ruby gem (unless we really need to adjust Resource classes to handle this surprising response format) but I'm not sure where else to report it, and it's of particular business concern for me right now.

Since billing_info and ship_addresses can be mutated I was really hoping an invoice would include complete and accurate copies of the address information which was used to process a subscription instalment.

**Comment by bhelx** [comment]
@Sinetheta I just wanted to make sure this wasn't something going on with this library but it appears to be an issue that will have to be addressed at the API level. I'd suggest contacting support `support@recurly.com` and referencing this github issue. That way they can keep you up to date on when it will be fixed.
