### ISSUE TITLE
Pager cursor broken for accounts

### ISSUE THREAD

**Issue by pkopac** [recurly/recurly-client-ruby#375]
Please remove this line: https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource/pager.rb#L91

I had to monkey-patch the library, because we read the next cursor ourselves, which for accounts is now `123:123` instead of `123`. This line just silently removes `:123` and we got `HTTP 400 Bad request: cursor format is invalid`

PS: the reason it works in the library is that you just `load_from` the next URL without parsing it.

**Comment by drewish** [comment]
Yeah good point. The cursor format changed in API V2.3 to support the updated_at sorting/filtering. I'll put in a ticket for this.
