### ISSUE TITLE
"[WARNING] Recurly logger" messages should be disableable

### ISSUE THREAD

**Issue by bughit** [recurly/recurly-client-ruby#381]
whether logging is off or on there is no reason to keep warning forever
```ruby
    def logger=(logger)
      if ENV['RECURLY_INSECURE_DEBUG'].to_s.downcase == 'true'
        @logger = logger
        puts <<-MSG
        [WARNING] Recurly logger enabled. The logger has the potential to leak
        PII and should never be used in production environments.
        MSG
      else
        puts <<-MSG
        [WARNING] Recurly logger has been disabled. If you wish to use it,
        only do so in a non-production environment and make sure
        the `RECURLY_INSECURE_DEBUG` environment variable is set to `true`.
        MSG
      end
    end
```

**Comment by bhelx** [comment]
@bughit If you want to disable the message, don't call `logger=` in your codebase. If you are using rails, the railtie might be automatically doing that.

**Comment by bughit** [comment]
I am using rails so yes, the railtie is calling logger=

**Comment by bhelx** [comment]
@bughit I'll have a follow up PR to alter the railtie so it does not call this in production.

**Comment by bughit** [comment]
That will make it impossible to turn on logging?  Seems too drastic.

Logging can off by default, but it should be possible to turn it on, while also avoiding incessant warnings.
