### ISSUE TITLE
What is the change from 2.11.3 to 2.11.4

### ISSUE THREAD

**Issue by Domon** [recurly/recurly-client-ruby#383]
Hi,

According to https://dev.recurly.com/page/ruby-updates and https://rubygems.org/gems/recurly/versions, `2.11.4` is the latest version of `2.11.x`.

However, I couldn't find either a `2.11.4` tag or any change log on Github.

Could anyone kindly add the tag or indicate where those could be found?

Thanks.

**Comment by bhelx** [comment]
@Domon Thanks for the question. 2.11.4 is a security patch that was only released to rubygems. We will be updating the github releases this week. You can only find it on rubygems right now:
https://rubygems.org/gems/recurly/versions/2.11.4 . If you want access to the code but don't use bundler or rubygems, you can use the "download" option on that page.
