### ISSUE TITLE
Strange pager behavior probable related to Enumerable

### ISSUE THREAD

**Issue by ethervoid** [recurly/recurly-client-ruby#423]
Hi!

I'm experiencing some weird behaviour regarding invoices objetct from recurly account.

In the version `2.7.3` if we get and empty invoices collection we can do the following:

```
=> #<Recurly::Resource::Pager:0x00000007d7a738 @parent=#<Recurly::Account accept_language: nil, account_code: "foo", address: #<Recurly::Address address1: nil, address2: nil, city: nil, country: nil, phone: nil, state: nil, zip: nil>, cc_emails: nil, closed_at: nil, company_name: nil, created_at: Thu, 04 Oct 2018 09:59:22 +0000, email: "foo@bar", entity_use_code: nil, first_name: nil, hosted_login_token: "bar", last_name: nil, state: "active", tax_exempt: false, updated_at: Thu, 04 Oct 2018 09:59:22 +0000, username: "testrecurly", vat_location_valid: nil, vat_number: nil>, @uri="https://api.recurly.com/v2/accounts/foo/invoices", @etag=nil, @options={}, @resource_class=Recurly::Invoice, @count=nil, @collection=nil>
irb(main):003:0> u.recurly_account.invoices.last
=> nil
irb(main):004:0> u.recurly_account.invoices.any?
=> false
```

Right now we have a different result using that

```
=> #<Recurly::Resource::Pager:0x000000060141a8 @parent=#<Recurly::Account accept_language: nil, account_code: "foo", address: #<Recurly::Address address1: nil, address2: nil, city: nil, company: nil, country: nil, first_name: nil, geo_code: nil, last_name: nil, name_on_account: nil, phone: nil, state: nil, zip: nil>, cc_emails: nil, closed_at: nil, company_name: nil, created_at: Thu, 04 Oct 2018 09:59:22 +0000, email: "foo@bar", entity_use_code: nil, first_name: nil, has_active_subscription: false, has_canceled_subscription: false, has_future_subscription: false, has_live_subscription: false, has_past_due_invoice: false, has_paused_subscription: false, hosted_login_token: "bar", last_name: nil, preferred_locale: nil, state: "active", tax_exempt: false, updated_at: Thu, 04 Oct 2018 09:59:22 +0000, username: "testrecurly", vat_location_valid: nil, vat_number: nil>, @uri="https://api.recurly.com/v2/accounts/foo/invoices", @etag="etagfoo", @options={}, @resource_class=Recurly::Invoice, @collection=[], @links={}>
irb(main):012:0> u.recurly_account.invoices.any?
=> true
irb(main):019:0> u.recurly_account.invoices.all
=> []
irb(main):024:0> u.recurly_account.invoices.count
=> 0
```

I've read the code and the Pager class inherits from Enumerable so it should be the same. I've also done a `reload` call and nothing.

Any clue? it looks like a bug

**Comment by bhelx** [comment]
@ethervoid Does normal enumeration work for you?

```ruby
u.recurly_account.invoices.each do |invoice|
  puts invoice.uuid
end
```

**Comment by ethervoid** [comment]
@bhelx it's weird using the same user than before, right now I have one invoice when in the past was 0. Maybe it takes some time to process the subscription and the model knows that there is one invoice in process?

**Comment by bhelx** [comment]
@ethervoid I can give you a more precise explanation if you share some more code for context, what are you doing right before fetching the invoices? Although invoices are created in the context of the request, they are processed asynchronously and might take 1-3 seconds. Subscriptions also have some async behavior.

**Comment by aaron-suarez** [comment]
Closing this out because as far as we can tell, this is not related to enumerable, it is probably due to the async behavior described in the last two posts. If using normal enumeration (as described in the [dev docs](https://dev.recurly.com) and https://github.com/recurly/recurly-client-ruby/issues/423#issuecomment-427065576 is causing a problem, please feel free to reopen the issue and provide further details.
