### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by hillia** [recurly/recurly-client-ruby#425]
```
/usr/local/lib/ruby/2.3.0/net/protocol.rb:44 in connect_nonblock
/usr/local/lib/ruby/2.3.0/net/protocol.rb:44 in ssl_socket_connect
/usr/local/lib/ruby/2.3.0/net/http.rb:928 in connect
/usr/local/lib/ruby/2.3.0/net/http.rb:863 in do_start
/usr/local/lib/ruby/2.3.0/net/http.rb:852 in start
/gems/recurly-2.11.4/lib/recurly/api/net_http_adapter.rb:77 in request
/gems/recurly-2.11.4/lib/recurly/api.rb:53 in get
/gems/recurly-2.11.4/lib/recurly/resource/pager.rb:220 in load_from
/gems/recurly-2.11.4/lib/recurly/resource/pager.rb:126 in load!
/gems/recurly-2.11.4/lib/recurly/resource/pager.rb:91 in each
lib/api/recurly/client.rb:197 in first
197:  subscription = subscriptions.first if subscriptions
```
Versions:
recurly (2.11.4)
ruby (2.3.0)
OpenSSL 1.0.1k 8 Jan 2015

I intermittently get the above error when using the Recurly Ruby library to make an API call. I've seen it happen on other APIs as well, including `GET /accounts/:account_code/subscriptions`, `GET /accounts/:account_code`, `GET /accounts/:account_code/billing_info`.

From what I can tell, the error occurs because the client attempts to connect with SSLv2 or v3, but the server does not support this. I'm not sure why it attempts with those versions, since the default behavior of Net::HTTP is to use the highest version supported by the server, and according to [SSLAnalyzer](https://sslanalyzer.comodoca.com/?url=https://wheelhouse.recurly.com) the server it only implements `TLSv1.2`.

I therefore tried restricting our SSL versions in order to avoid this error (as well as avoid SSL vulnerabilities) by running the following code in a Rails initializer:

```
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:options] |= OpenSSL::SSL::OP_NO_SSLv2
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:options] |= OpenSSL::SSL::OP_NO_SSLv3
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:options] |= OpenSSL::SSL::OP_NO_COMPRESSION
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers] = 'TLSv1.2:!aNULL:!eNULL'
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] = 'TLSv1_2'

# Just to be absolutely sure
Recurly::API.net_http = {
    ssl_version: :TLSv1_2
}
```

This stopped the above error, but now I am intermittently getting:

`SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number`

which seems to imply that the client is still occasionally trying to connect with SSLv3 but it is disallowed. Again this is strange because the default behavior should be to use the highest SSL version implemented by the server.

Is it possible that a few of Recurly's API servers still use SSLv3, and we are occasionally being load-balanced to those? Or is there some configuration that needs to happen in the Recurly library to avoid this?

**Comment by bhelx** [comment]
@hillia we only support versions >= TLSv1.2 due to new PCI requirements. I'm surprised that it's working intermittently, but these issues often have to do with your ruby or openssl dependencies. My gut is telling me that your openssl version is too old. Is that the version of openssl that was used when compiling ruby? Give this script a shot on your server and let us know what it gives you:

```ruby
require 'net/https'
require 'json'

uri = URI("https://www.howsmyssl.com/")
http = ::Net::HTTP.new uri.host, uri.port
http.use_ssl = true

data = JSON.parse(http.get('/a/check').body)

puts "TLS Version Negotiated: #{data['tls_version']}"
```

**Comment by bhelx** [comment]
Also, I wanted to ask if this is something that has started happening for you recently? Is there anything that has changed on your end? Or is this a new integration?

**Comment by hillia** [comment]
Output:
`TLS Version Negotiated: TLS 1.2`

I don't believe that is the same OpenSSL version that was used to compile our current Ruby version. But TLS 1.2 has been supported by OpenSSL as of March 2012. I could try upgrading OpenSSL, but since I can't reliably reproduce the error, it would be difficult to test outside of updating all of our live servers.

We began seeing these errors on June 1, 2018. I don't see any major updates made around that time, either to our ruby version, our openssl version or the machines they're running on.

We see maybe 2-5 of these errors a day, and--while it's mostly just an annoyance at this point--it sometimes delays a user's invoices by a day.

**Comment by aaron-suarez** [comment]
@hillia Have you tried setting `min_version` on the SSL_CONTEXT? Not sure if that's available in your version of Ruby, but if it is, that might prevent the library from trying to connect with SSLv3.

https://ruby-doc.org/stdlib-2.5.1/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html#method-i-min_version-3D

**Comment by hillia** [comment]
I have not. I assumed the `TLSv1.2` cipher + `OpenSSL::SSL::OP_NO_SSLv3` flag would prevent that, but I'll give it a try.

**Comment by bhelx** [comment]
> I don't believe that is the same OpenSSL version that was used to compile our current Ruby version. But TLS 1.2 has been supported by OpenSSL as of March 2012. I could try upgrading OpenSSL, but since I can't reliably reproduce the error, it would be difficult to test outside of updating all of our live servers.

I think these 2 commands should tell you specifically openssl ruby is using. The latter command tells you the compile-time version:

```
ruby -r openssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
ruby -r openssl -e 'puts OpenSSL::OPENSSL_VERSION'
```

> We began seeing these errors on June 1, 2018. I don't see any major updates made around that time, either to our ruby version, our openssl version or the machines they're running on.

That's kind of near, but before, we shut off support for 1.0 and 1.1: https://dev.recurly.com/page/tls-v10-deprecation

**Comment by bhelx** [comment]
BTW, we don't recommend you explicitly specify versions or ciphers unless you must or for testing purposes. Ideally those can be negotiated with the server (which changes with the security landscape).

Hopefully we can get to the bottom of why this is happening and you can remove any customization you have.

**Comment by hillia** [comment]
```
>> ruby -r openssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
OpenSSL 1.0.1k-fips 8 Jan 2015
>> ruby -r openssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.1k 8 Jan 2015
```

**Comment by aaron-suarez** [comment]
@hillia If this is still a problem, I have some more information that might be helpful. 

The “sslv3” in the error message can be a red herring for the underlying issue. TLS is really a minor version bump to the SSLv3 protocol; TLSv1.2 is also known as SSL protocol version 3.3. So, the TLS handshake code shares a lot with the SSLv3. Before the protocol is negotiated, it’s common to see an error message about “sslv3". Check out the Illustrated TLS Connection @ https://tls.ulfheim.net/ for a bit more information.

You might search for any other code in your app & vendored gems that may have monkey patched net/http. After the POODLE vulnerability, several people started to force TLS. Unfortunately, at the time `TLSv1_2` was not an option so `TLSv1` was frequently used instead. This worked for requiring TLS but downgraded TLSv1.2 to 1.0. Grep for `TLSv1` to find any relevant code.

Also try validating that `:TLSv1_2` is a supported method:

```puts 'Includes TLSv1_2: %s' % OpenSSL::SSL::SSLContext::METHODS.include?(:TLSv1_2)```

Hopefully upgrading OpenSSL and searching these places will uncover/prevent the issue. Please report back if you've done all of these things and are still having issues.

Thanks to @isaachall for the additional suggestions.

**Comment by aaron-suarez** [comment]
@hillia Are there any updates on this? Are you still seeing this error on newer versions of the Ruby client library?

**Comment by hillia** [comment]
Not yet. I'll try bumping the client version and let you know.

**Comment by aaron-suarez** [comment]
Closing this out because it appears to only affect older versions of OpenSSL, Ruby and the Recurly gem. If anyone sees this issue on the latest version of OpenSSL, Ruby and this gem, please comment here or open a new issue. Thank you.
