### ISSUE TITLE
`Recurly::Webhook::NotificationError` raising `not a recognized notification` for multiple notifications

### ISSUE THREAD

**Issue by lauramosher** [recurly/recurly-client-ruby#430]
When using `Recurly::Webhook.parse()`, the following notifications are not recognized:

- `transaction_status_updated_notification`
- `updated_invoice_notification` (deprecated in Credit Invoices, but still being sent; and it may continue being sent based on [this message](https://dev.recurly.com/page/webhooks#section-updated-invoice))

Version: `2.17.1`

**Comment by aaron-suarez** [comment]
Thanks for pointing this out. I added a note to the documentation here https://dev.recurly.com/v2.16/page/ruby#handle-webhooks.

Please feel free to catch these errors and swallow them. But of course, be sure to let us know if you are trying to actually use a webhook that is for whatever reason not implemented in the library.
