### ISSUE TITLE
How to stop annoying: "[WARNING] Recurly logger has been disabled" on 2.10.5 version?

### ISSUE THREAD

**Issue by crysper** [recurly/recurly-client-ruby#435]
I'm well aware that you made an update for other version to disable this message, but you forgot to also update the 2.10.5 version.

I can't upgrade to 2.16, that's why I need a way to disable this, maybe a monkey patch or something?

**Comment by aaron-suarez** [comment]
@crysper The code that prints out the warning is in the `logger=` method. Are you doing something similar to the following somewhere in your implementation?

```ruby
Recurly.logger = Logger.new STDOUT
```

**Comment by crysper** [comment]
No, I'm just using Rails and I can see this code:
`initializer :recurly_set_logger do
      Recurly.logger = Rails.logger
    end`

on 2.10.5 version of the gem which was removed on other versions

**Comment by aaron-suarez** [comment]
We strongly recommend that you upgrade to the latest version for security and bug fixes as well as feature upgrades. If you need help upgrading from 2.10.5 to 2.16, please feel free to contact Recurly support.

However, in the mean time, if you absolutely must disable it right now, perhaps you can build from source and cherry-pick that commit from git. It was added in 1e4c7567eea314fe496166b9176c29d32f76224a.
