### ISSUE TITLE
Recurly::Coupon#generate get nil error

### ISSUE THREAD

**Issue by yakjuly** [recurly/recurly-client-ruby#453]
```
coupon = Recurly::Coupon.find("a_bulk_coupon_code_prefix")
coupon.generate(1).first.coupon_code
```
It has two issues.
1. It may return a used coupon_code, not a unused one.  (it happens once)
2. It may raise `NoMethodError · undefined method '[]' for nil:NilClass`.

I am using recurly v2.16.0

**Comment by drewish** [comment]
How long ago did you last hit this? There was a fix that went out today to address an issue with `unique_coupon_codes` not being the root element in the response.

**Comment by yakjuly** [comment]
Issue 1  return a used coupon code happens yesterday.

'nil' exception happens today, it is probably true caused by server side.

**Comment by yakjuly** [comment]
@drewish Just tested, still get nil Exception.
```
1: from /usr/local/bundle/gems/recurly-2.16.0/lib/recurly/coupon.rb:106:in `generate'
NoMethodError (undefined method `[]' for nil:NilClass)
```

**Comment by aaron-suarez** [comment]
The server-side fix for this issue was deployed today, it should work now. I tested on my sandbox site and it works for me. Please feel free to comment or re-open if you continue to experience issues.
