### ISSUE TITLE
undefined method `private_key=' for Recurly::JS:Module

### ISSUE THREAD

**Issue by silambarasanmkce** [recurly/recurly-client-ruby#477]
i'm using a method  Recurly.js.private_key it is showing undefined method `private_key=' for Recurly::JS:Module

**Comment by bhelx** [comment]
@silambarasanmkce This property was removed in 2.17.0. See the Upgrade Notes for details: https://github.com/recurly/recurly-client-ruby/releases/tag/2.17.0
