### ISSUE TITLE
API version 2.2 deprecation

### ISSUE THREAD

**Issue by spyrbri** [recurly/recurly-client-ruby#478]
I see that the API version that the gem uses is hardcoded to 2.20. Is there a plan on moving to a later version since it looks like this is going to be deprecated soon.

https://blog.recurly.com/recurly-api-v2.6-and-lower-deprecation-and-end-of-life?utm_content=93646882&utm_medium=social&utm_source=twitter&hss_channel=tw-57871527

https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/api.rb#L20

**Comment by aaron-suarez** [comment]
Hi there @spyrbri, thanks for your question. Based on the fact that you closed this out, I'm sure you realized that 2.20 is the most recent version of the API, released after 2.19. I just wanted to explicitly answer the question in case someone comes across this in some sort of search.

**Comment by spyrbri** [comment]
Yes, sorry I got scared by a recent blogpost but then I realized I was mistaken.
