### ISSUE TITLE
.find_each throws Timeout::Error occasionally

### ISSUE THREAD

**Issue by wharle90** [recurly/recurly-client-ruby#526]
This problem started for us within the last week. Nightly, we pull a list of accounts and subscriptions from recurly and update some mrr values locally from them. This has always worked for us with no issue. Now, 3 out of the last 5 nights, while doing this process we have gotten a timeout which has caused the process to stop. Has there been a change here or is there maybe a way that I can pickup and retry from the current element I'm find_each-ing at when the timeout occurs?

Error: /opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
/opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:880:in `open'
/opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
/opt/rubies/2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/opt/rubies/2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
/home/upcity/upcity-production/shared/bundle/ruby/2.3.0/gems/recurly-2.17.4/lib/recurly/api/net_http_adapter.rb:77:in `request'
/home/upcity/upcity-production/shared/bundle/ruby/2.3.0/gems/recurly-2.17.4/lib/recurly/api.rb:53:in `get'
/home/upcity/upcity-production/shared/bundle/ruby/2.3.0/gems/recurly-2.17.4/lib/recurly/resource/pager.rb:278:in `load_from'
/home/upcity/upcity-production/shared/bundle/ruby/2.3.0/gems/recurly-2.17.4/lib/recurly/resource/pager.rb:153:in `next'
/home/upcity/upcity-production/shared/bundle/ruby/2.3.0/gems/recurly-2.17.4/lib/recurly/resource/pager.rb:147:in `find_each'

**Comment by bhelx** [comment]
@wharle90 Thanks for reporting. It's hard to imagine this is related to the ruby client, but I can do some investigation. Have you filed a support ticket? I'd suggest you do so in parallel if you have not.

Also, I assume you are calling `find_each` on the accounts endpoint?

**Comment by bhelx** [comment]
@wharle90 did you file a support ticket? Is this something you are still experiencing?

**Comment by joannasese** [comment]
@wharle90 if you're still having issues, please let us know. I'll close this ticket for now.
