### ISSUE TITLE
Undefined method cast

### ISSUE THREAD

**Issue by kevinjcoleman** [recurly/recurly-client-ruby#536]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Describe the bug**

We have an `ActiveRecord` class called `Invoice` and for some reason this was sometimes breaking specs. To fix this, I added:
```
elsif type == :Invoice
  Resources::Invoice
```
to `lib/recurly/schema.rb:46` and that got specs passing correctly.

**Expected behavior**
Gem should not be trying to cast the value of an external class.
**Your Environment**
- Which version of this library are you using? - 3.1

**Comment by douglasmiller** [comment]
Hey @kevinjcoleman 

Thank you for bringing this to our attention. I was able to reproduce the behavior that you're describing in a `pry` session:

```ruby
[1] pry(main)> require 'recurly'
=> true
[2] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Recurly::Resources::Invoice
[3] pry(main)> class Invoice; end
=> nil
[4] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Invoice
```

I believe that this diff will solve the issue for all other constants. I'll verify tomorrow and get this released asap.

```diff
diff --git a/lib/recurly/schema.rb b/lib/recurly/schema.rb
index dd34e7d..d0ec7c1 100644
--- a/lib/recurly/schema.rb
+++ b/lib/recurly/schema.rb
@@ -43,10 +43,10 @@ module Recurly
 
       if type == :Address
         Resources::Address
-      elsif Requests.const_defined?(type)
-        Requests.const_get(type)
-      elsif Recurly::Resources.const_defined?(type)
-        Resources.const_get(type)
+      elsif Requests.const_defined?(type, false)
+        Requests.const_get(type, false)
+      elsif Recurly::Resources.const_defined?(type, false)
+        Resources.const_get(type, false)
       else
         raise ArgumentError, "Recurly type '#{type}' is unknown"
       end
```

**Comment by kevinjcoleman** [comment]
@douglasmiller thanks for the quick fix!
