### ISSUE TITLE
Implement way to actually get ErrorMayHaveTransaction

### ISSUE THREAD

**Issue by hkmaly** [recurly/recurly-client-ruby#540]
**Describe the bug**

When error has class Recurly::Errors::TransactionError, error.recurly_error is of type Recurly::Resources::Error. It should be Recurly::Resources::ErrorMayHaveTransaction.

The problem seem to be caused by Recurly::JSONParser.parse(nil, error.get_response.body) returning Recurly::Resources::Error.

**To Reproduce**

... not sure how to fully reproduce without recurly js ... however, just the second part:
```
x = "{\"error\":{\"type\":\"transaction\",\"message\":\"Your transaction was declined. Please use a different card or contact your bank.\",\"transaction_error\":{\"object\":\"transaction_error\",\"transaction_id\":\"lxx9bjmrcra5\",\"category\":\"soft\",\"code\":\"declined\",\"message\":\"Your card was decline
d. In order to resolve the issue, you will need to contact your bank.\",\"merchant_advice\":\"The customer's bank has declined their card. The customer wil
l need to contact their bank to learn the cause.\",\"three_d_secure_action_token_id\":null}}}"
pp Recurly::JSONParser.parse(nil, x)
```

**Expected behavior**

Recurly::JSONParser.parse(nil, x) should return Recurly::Resources::ErrorMayHaveTransaction
With error of type Recurly::Errors::TransactionError, error.recurly_error should be Recurly::Resources::ErrorMayHaveTransaction.

**Your Environment**

recurly-3.1.0
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

**Comment by hkmaly** [comment]
I suppose following code might implement it correctly:
```
module Recurly
  class JSONParser
    def self.from_json(data)
      type = if data.has_key?("error")
                if data['error']['type'] == 'transaction'
                  "error_may_have_transaction"
                else
                 "error"
               end
             else
               data["object"]
             end
      klazz = self.recurly_class(type)

      unless klazz
        raise ArgumentError, "Unknown resource for json type #{type}"
      end

      data = data["error"] if klazz == Resources::Error || klazz == Resources::ErrorMayHaveTransaction

      klazz.cast(data)
    end
  end
end
```

**Comment by bhelx** [comment]
Thanks! We found the same issue with the other clients last week: https://github.com/recurly/recurly-client-net/pull/465

We'll prepare a fix for it.
