### ISSUE TITLE
It's hard to find out what payment method was used

### ISSUE THREAD

**Issue by hkmaly** [recurly/recurly-client-ruby#543]
There is payment_method object as part of transaction, but it doesn't actually show what payment method was used. Sure, if card_type is set it would probably be credit card and billing_agreement_id suggests paypal, but it would be better to have explicit field, especially considering more payment methods may be added.

According to API documentation, it might be possible to use the "object" field, but that one is empty when using this gem (and according to get_response, the value is "paypal_billing_agreement" for paypal, which is not entirely ideal, but it would be better than alternative).

**To Reproduce**

```
client = EinNews::RecurlyClient.new
pp client.get_invoice(invoice_id: 'number-' + 12992.to_s)
pp client.get_invoice(invoice_id: 'number-' + 12988.to_s)
pp client.get_transaction(transaction_id: 'lyi9xk9rbz5w')
```

**Expected behavior**

I would expect there will be something with value "credit_card" in first case and "paypal" in second (and third) case.

**Your Environment**

recurly-3.1.0
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

**Comment by bhelx** [comment]
@hkmaly I was just working on a fix for this when you posted. There should be a payment_method attribute on the BillingInfo objects and the Transactions. Those have an `object` attribute explaining the method:

```
[2] pry(main)> transaction.payment_method.object
=> "credit_card"
``` 

The object attribute was not being parsed.

see docs for possible values: https://developers.recurly.com/api/v2019-10-10/index.html#operation/get_transaction

**Comment by hkmaly** [comment]
Thanks.

So I guess I need payment_method.object.gsub(/_billing_agreement$/, '').gsub(/_info$/,'').gsub(/_/,' ') and hope nothing weird gets added ...
