### ISSUE TITLE
Update Faraday Version Maximum

### ISSUE THREAD

**Issue by monicagallegos** [recurly/recurly-client-ruby#548]
Hello! Are there any plans underway to update the max-version constraint on the Faraday dependency? I see here: https://github.com/recurly/recurly-client-ruby/pull/518 that a max constraint of 0.16 was added to get specs to pass. Would love for this to be revisited soon so that the recurly gem does not prevent me from adding gems that use higher versions of faraday.

**Comment by bhelx** [comment]
@monicagallegos The library was not working for versions `> 0.16` so we could not support it. I'm happy to look into that again. Perhaps we just constrain it at `1.0.0`. What version are you running out of curiosity?

**Comment by monicagallegos** [comment]
@bhelx thank you for your response and yes if you could look into the issue that would be greatly appreciated. Down with the 1.0.0 constraint. I am currently using Faraday at 17.1

**Comment by bhelx** [comment]
@monicagallegos I've released this as `3.2.2`:

Rubygems: https://rubygems.org/gems/recurly/versions/3.2.2
Notes: https://github.com/recurly/recurly-client-ruby/releases/tag/3.2.2

Thanks for posting. Let us know if you have any further issues.

On another note, we were just discussing removing the Faraday dependency last week. This is probably something we will want to look into as people start to get spread out b/w their `0.x` versions and their `1.x` versions. It's a nice crutch to get the library running but is going to be straining to support long term.

**Comment by monicagallegos** [comment]
@bhelx Amazing. Thank you so much. You rock!

**Comment by bhelx** [comment]
@moni-ellevest #568 will go out in the next release (likely 3.4.0). On top of removing faraday, it has some other HTTP improvements worth updating to.
