### ISSUE TITLE
getting below error 

### ISSUE THREAD

**Issue by Anjali1982** [recurly/recurly-client-ruby#607]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Comment by Anjali1982** [comment]
SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failureSSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure

ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin15]

 openssl version -a
OpenSSL 1.1.1d  10 Sep 2019
built on: Tue Feb 11 23:40:31 2020 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -D_REENTRANT -DNDEBUG
OPENSSLDIR: "/usr/local/etc/openssl@1.1"
ENGINESDIR: "/usr/local/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1"
Seeding source: os-specific

**Comment by douglasmiller** [comment]
Hey @Anjali1982, thank you for reaching out to us. Could you provide a little more information about the SSL issue that you're experiencing? It would be helpful to know what version of the client library you are using. It may also be useful if you could provide a minimal code example that produces the error that you are experiencing.

**Comment by Anjali1982** [comment]
while executing the script written in ruby ,i am getting below error ,that scripts basically talks to Netapp controllers and create a zap session ...i get following error 

SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failureSSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure

**Comment by douglasmiller** [comment]
@Anjali1982 have you looked through [this similar issue](https://github.com/recurly/recurly-client-ruby/issues/425)?

Ultimately, the issue appears to be related to the TLS version that your system is attempting to use when negotiating a connection with Recurly API, which supports a minimum version of TLS v1.2.

It would be very helpful if you could share which version of the Recurly ruby client library that you are using.

Could you save this code snippet to `test.rb`:

```ruby
require 'recurly'

api_key = ENV.fetch('RECURLY_API_KEY')

client = Recurly::Client.new(api_key: api_key)

sites = client.list_sites
puts "Got #{sites.count} sites"
```

Then run it with this command (substituting `<YOUR_API_KEY>` with your own Recurly API key):

```shell
RECURLY_API_KEY=<YOUR_API_KEY> bundle exec ruby test.rb
```

**Comment by joannasese** [comment]
Hi @Anjali1982. As we have not heard from you, I'm going to go ahead and close this ticket. If you are still encountering issues, please open another ticket. We're happy to help!
