### ISSUE TITLE
uninitialized constant Recurly::Errors::ServiceNotAvailableError

### ISSUE THREAD

**Issue by jalhadi** [recurly/recurly-client-ruby#640]
**Describe the bug**
For some inputs, when `preview_purchase` is called on a client, the API returns `ServiceNotAvailableError`, but this causes an unhandled exception of `uninitialized constant Recurly::Errors::ServiceNotAvailableError`. I am unable to see the underlying API issue as the uninitialized constant error supersedes it.

**To Reproduce**
I've run into this issue when the state and zip code don't match, but have not been able to reproduce this issue consistently. I think the error might be related to https://github.com/recurly/recurly-client-python/issues/369 as we also use Avalara for tax purposes. This has only happened when calling `preview_purchase` on a `Recurly::Client` object.

**Expected behavior**
`ServiceNotAvailableError` should be a valid error class or `APIError` should be returned in this case so that the underlying input error can be inspected and handled gracefully.

**Your Environment**
recurly version: 3.5.0
ruby version: 2.7.0

**Comment by joannasese** [comment]
Hi @jalhadi. Thanks for reporting. We'll investigate.

**Comment by joannasese** [comment]
Hi @jalhadi just wanted to check in. We haven't forgotten about you. This is a quick fix and we're aiming to patch it early next week.

**Comment by joannasese** [comment]
Hi @jalhadi. We'll be adding `ServiceNotAvailableError` as a known error type. In addition, we will be merging [this PR](https://github.com/recurly/recurly-client-ruby/pull/641) after a few changes we requested are made.

**Comment by joannasese** [comment]
Hi @jalhadi. https://github.com/recurly/recurly-client-ruby/pull/641 has been merged. I'll close out this ticket.
