### ISSUE TITLE
Every method is returning wrong number of arguments

### ISSUE THREAD

**Issue by noctivityinc** [recurly/recurly-client-ruby#664]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Describe the bug**

We have an initializer that intis the recurly client:
```
 @recurly_client = Recurly::Client.new(api_key: Rails.application.credentials.dig(:recurly, :api_key))
```
but every single method, such as ```list_plans``` returns an ```ArgumentError```:

```
3.0.0 :002 > @recurly_client.list_plans
Traceback (most recent call last):
        1: from (irb):2:in `<main>'
ArgumentError (wrong number of arguments (given 1, expected 0))
3.0.0 :003 > @recurly_client.list_plans()
Traceback (most recent call last):
        2: from (irb):2:in `<main>'
        1: from (irb):3:in `rescue in <main>'
ArgumentError (wrong number of arguments (given 1, expected 0))
3.0.0 :004?> @recurly_client.list_plans({})
Traceback (most recent call last):
        2: from (irb):3:in `<main>'
        1: from (irb):4:in `rescue in <main>'
ArgumentError (wrong number of arguments (given 1, expected 0))
3.0.0 :005 > @recurly_client.list_plans(limit: 200)
Traceback (most recent call last):
        2: from (irb):4:in `<main>'
        1: from (irb):5:in `rescue in <main>'
ArgumentError (wrong number of arguments (given 1, expected 0))
```

**To Reproduce**

Steps to reproduce the behavior.

1. Clean rails app
2. Add gem 3.18.0
3. Create recurly.rb in initializers
4. Try to list the plans

**Expected behavior**

We expected to get a list of all current plans.

**Your Environment**

- Which version of this library are you using?
- recurly 3.18.0
- Which version of ruby are you using?
- Ruby 3.0

**Comment by douglasmiller** [comment]
Thank you for reporting this bug, @noctivityinc .

This appears to be an issue with ruby 3.0 and the updated handling of the double splat operator. We will investigate what needs to be updated and keep you informed.

**Comment by noctivityinc** [comment]
Is there a work around in the meantime?

**Comment by douglasmiller** [comment]
I just opened a pull request that will fix the issue that you reported. Once it is merged, we will publish the fixed client.

**Comment by douglasmiller** [comment]
@noctivityinc The [3.18.1 gem](https://rubygems.org/gems/recurly/versions/3.18.1) has been published. Thanks again for reporting this!

**Comment by noctivityinc** [comment]
Thank you.  Ill give it a try.

**Comment by noctivityinc** [comment]
@douglasmiller I think you missed one.  The `Recurly::Pager.count` method needs to be updated to work with Ruby 3.0
