### ISSUE TITLE
Resuming paused subscription fails validation

### ISSUE THREAD

**Issue by noctivityinc** [recurly/recurly-client-ruby#676]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Describe the bug**

Is a subscription is paused, running ```resume_subscription``` fails.

**To Reproduce**

Steps to reproduce the behavior.

1. Create an active subscription
2. Pause like this: 
```
   subscription_pause = {
      remaining_pause_cycles: 1
    }
    subscription = RECURLY_CLIENT.pause_subscription(
      subscription_id: subscription_id,
      body: subscription_pause
    )
```
3. Try to resume like this
```
    subscription = RECURLY_CLIENT.resume_subscription(
      subscription_id: subscription_id,
      body: subscription_pause
    )
```
4. You will get this error:
``` 
{"error":{"type":"validation","message":"Subscription Unable to resume active subscription.","params":[{"param":"subscription","message":"Unable to resume active subscription."}]}}
```

**Expected behavior**

Two things:
1. I expected that when I paused the subscription state would change to `paused` from `active`, which does not happen
2. When I try to resume a subscription I just paused, it would resume

**Your Environment**

recurly (3.18.1)
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
rails 6.1.3

**Comment by douglasmiller** [comment]
The `pause_subscription` operation will pause the subscription at the next renewal date. This can make it difficult to test the `resume_subscription` operation as you cannot immediately put a subscription into the `paused` state.

This is expected behavior since the currently active subscription should remain active until the end of the current billing cycle.

**Comment by noctivityinc** [comment]
So you're saying that before we issue a resume_subscription we need to
first CHECK to see if it is "active" or "paused" and THEN if active issue
pause_subscription with a period of 0 and if paused them use resume?

That seems grossly inefficient.  Shouldn't that logic take place on the
SERVER side?  If you are allowing us to use pause_subscription when they
have an active subscription correctly then shouldnt you handle
resume_subscription under both circumstances?
