### ISSUE TITLE
Network error does not exist

### ISSUE THREAD

**Issue by scsmith** [recurly/recurly-client-ruby#684]
https://github.com/recurly/recurly-client-ruby/blob/a4bc826b4da8876ac138b38775d58c265fd6c1ad/lib/recurly/client.rb#L215 raises a network error. This error seems to have been removed. I'm happy to make a PR but I'm not sure what error it should be, APIError or something more specific?

**Comment by douglasmiller** [comment]
Thank you for reporting this issue, @scsmith. We will fix this and provide an updated release soon.
