### ISSUE TITLE
`sort` and `order` params are being ignored when listing account transactions

### ISSUE THREAD

**Issue by pjg** [recurly/recurly-client-ruby#742]
**Describe the bug**

`sort` and `order` params are being ignored when listing account transactions.

**To Reproduce**

```ruby
client = Recurly::Client.new(api_key: 'xxx')
client.list_account_transactions(account_id: "code-test-code", params: { sort: 'created_at', order: 'desc' }).each { |t| puts "#{t.created_at}: #{t.id}" }
```

gives:

```
2021-12-28T20:22:46+00:00: q4lakiqvg01e
2021-12-28T15:06:39+00:00: q4jq654lewqs
```

And using `order: 'asc'`:

```ruby
client.list_account_transactions(account_id: "code-test-code", params: { sort: 'created_at', order: 'asc' }).each { |t| puts "#{t.created_at}: #{t.id}" }
```

gives the exact same, now incorrect list (should be reversed):

```
2021-12-28T20:22:46+00:00: q4lakiqvg01e
2021-12-28T15:06:39+00:00: q4jq654lewqs
```

Note that a similar `list_account_subscriptions` method works properly.

**Expected behavior**

`order` param should be respected and the list should be reversed.

**Your Environment**

- Which version of this library are you using?

Ruby's recurly gem v4.10.0.

- Which version of ruby are you using?

2.6.8

**Comment by douglasmiller** [comment]
Thank you for reporting this issue, @pjg.

This does appear to be a valid issue with the API. I will escalate this issue and leave your issue open until there is an update.

**Comment by douglasmiller** [comment]
@pjg the fix for this issue has been deployed to the production environment.

Thank you again for reporting this to us. Please let us know if you encounter any other issues.

**Comment by pjg** [comment]
@douglasmiller thank you for fixing this!
