### ISSUE TITLE
documentation github page not found

### ISSUE THREAD

**Issue by gagalago** [recurly/recurly-client-ruby#791]
**Describe the bug**

https://recurly.github.io/recurly-client-ruby/ is not found and is referenced in many place (readme of this repo, [api references](https://developers.recurly.com/api/)...) 

**To Reproduce**

go on https://recurly.github.io/recurly-client-ruby/

**Expected behavior**

see ruby documentation

**Comment by douglasmiller** [comment]
Thank you for letting us know about this, @gagalago ! We have restored the documentation page
