### ISSUE TITLE
Transaction object is filled with nil values when there were some credits in the Sub after a Transaction.create call

### ISSUE THREAD

**Issue by hgcode** [recurly/recurly-client-ruby#99]
If you call transactions.create(...) etc,.. on a sub that has credits, and the transaction amount is less than those credits. Recurly returns a 204 no content msg, but the gem returns you just the Transaction object filled with nil stuff... 

Confirmed this issue with Recurly's support, you might want to make this a bit smarter, save people some headaches. 

Also, calling the transaction.create does generate an Invoice.. and I have no way of getting that invoice from that Transaction object without a work around of just going and fetching the last invoice for the subscription. Thanks!

**Comment by bhelx** [comment]
@hgcode @homezada I'm being told this issue was resolved. If you are still having a problem with it please re-open and I'd be happy to talk about and work on a fix.
